### ISSUE TITLE
Gladys fails to start using mongodb

### ISSUE THREAD

**Issue by moonstruck** [GladysAssistant/Gladys#11]
So far I've followed the instructions according to README. I get Gladys run perfectly with mysql settings. But when I run node app.js with mongodb settings it fails.

Last commit: 98ea1cf6762cedc8ef6dccefe4c68b57aa6f963e

Mongodb settings:

```
glnv: {
    adapter: 'sails-mongo',
    host: 'localhost',
    port: 27017,
    // user: 'username',
    // password: 'password',
    database: 'glnv'
  },
```

Database and collections are being created after running node app.js

Error messages:

```
node app.js
info: User hook policies loaded from /home/vagrant/glnv/api/hooks/example/policies.
info: User hook config loaded from /home/vagrant/glnv/api/hooks/example/config.
info: User hook models loaded from /home/vagrant/glnv/api/hooks/example/lib/../models.
info: User hook services loaded from /home/vagrant/glnv/api/hooks/example/lib/../services.
info: User hook controllers loaded from /home/vagrant/glnv/api/hooks/example/lib/../models.
info: 
info:                .-..-.
info: 
info:    Sails              <|    .-..-.
info:    v0.11.0             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in `/home/vagrant/glnv`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Sun Jun 14 2015 03:29:02 GMT+0000 (UTC)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------

/home/vagrant/glnv/node_modules/sails-mongo/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
TypeError: Object #<bound> has no method 'query'
    at Object.module.exports.scheduleAllAlarms (/home/vagrant/glnv/api/services/AlarmService.js:134:9)
    at Object.bound [as scheduleAllAlarms] (/home/vagrant/glnv/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Object.module.exports.onStart (/home/vagrant/glnv/api/services/StartService.js:29:16)
    at Object.bound [as onStart] (/home/vagrant/glnv/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /home/vagrant/glnv/config/bootstrap.js:19:18
    at wrapper (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
    at applyInOriginalCtx (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at _normalizeCallback.callback.success (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at /home/vagrant/glnv/node_modules/sails/node_modules/waterline/lib/waterline/query/dql/destroy.js:123:11
    at /home/vagrant/glnv/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:189:25
    at bound.<anonymous> (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/lib/waterline/utils/schema.js:151:44)
    at fn (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/lib/waterline/utils/callbacksRunner.js:136:10)
    at iterate (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:181:13)
    at Object.async.eachSeries (/home/vagrant/glnv/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:197:9)
```

**Comment by Pierre-Gilles** [comment]
That's completely normal, Gladys is built to run with MySQL. Sometimes Gladys needs to perform very specific request that shouldn't be done with sailjs ORM, so it's done by doing MySQL raw queries (for performance). 

And in fact Gladys couldn't be built with MongoDB, because the data Model has a lot of relationships, the data model need a relational database :) ( for more informations why MongoDB is not adapted sometimes : http://www.sarahmei.com/blog/2013/11/11/why-you-should-never-use-mongodb/comment-page-1/ )

But you are completely right, I should remove the defaults MongoDB connections lines in the config/connections.js folder, it was generated by sailsjs by default :)

Thanks for the feedback !
