### ISSUE TITLE
How to populate database

### ISSUE THREAD

**Issue by ghost** [GladysAssistant/Gladys#131]
Hello, 
i m trying again Gladys, but i m struck on my installation

so i m make a frech install on a ubuntu 16.04 lts minimal, and when i lunch gladys : 

```

stagiaire@Jasper:~/gladys$ node app.js
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.

=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=
WARNING: You currently have your default CORS settings configured to allow
all requests from all origins, with credentials.  This may leave your app
open to attack by third-party sites!  Consider making your `origins` setting
more restrictive or setting `credentials` to false, or else make certain that
none of your routes perform sensitive actions or reveal secure information.
=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

Gladys version : 3.3.3
No brain file detectedError: ENOENT: no such file or directory, open './cache/classifier.json'
Gladys brain loaded with success !

               .-..-.

   Sails              <|    .-..-.
   v0.12.11            |\
                      /|.\
                     / || \
                   ,'  |'  \
                .-'.-==|/_--'
                `--'-------'
   __---___--___---___--___---___--___
 ____---___--___---___--___---___--___-__

Server lifted in `/home/stagiaire/gladys`
To see your app, visit http://localhost:8080
To shut down Sails, press <CTRL> + C at any time.

-------------------------------------------------------
:: Sat Dec 17 2016 13:03:27 GMT+0100 (CET)

Environment : production
Port        : 8080
-------------------------------------------------------
Unhandled rejection Error: ER_NO_SUCH_TABLE: Table 'gladys.module' doesn't exist
    at Query.Sequence._packetToError (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
    --------------------
    at Protocol._enqueue (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:201:25)
    at __QUERY__ (/home/stagiaire/gladys/node_modules/sails-mysql/lib/adapter.js:107:22)
    at afterwards (/home/stagiaire/gladys/node_modules/sails-mysql/lib/connections/spawn.js:84:5)
    at /home/stagiaire/gladys/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at Handshake.onConnect (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:59:7)
    at Handshake.Sequence.end (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.Sequence.OkPacket (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/stagiaire/gladys/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

Gladys is up to date !
```

so m y question is how populate database of gladys please ?

**Comment by lTimeLordl** [comment]
Run `node init.js && grunt buildProd` before start Gladys in production.

This command should create tables and compile assets.

**Comment by promachos** [comment]
just retest it its working :)
