### ISSUE TITLE
[Zigbee2Mqtt] Wrong value in MQTT message causes Service crash

### ISSUE THREAD

**Issue by cicoub13** [GladysAssistant/Gladys#1426]
**Describe the bug**

When a device sends a value not compatible with Gladys Zigbee2Mqtt, the zigbee2mqtt service crash

https://community.gladysassistant.com/t/dashboard-evolutions-bugs-etc/5150/113#ajout-des-logs-rseau-1

**Logs**

```
2022-02-03T07:36:35+0100 <warn> handleMqttMessage.js:96 () Zigbee2mqtt device RadiateurSalleaManger, feature boost_heating not configured in Gladys.
2022-02-03T07:36:35+0100 <warn> handleMqttMessage.js:96 () Zigbee2mqtt device RadiateurSalleaManger, feature boost_heating_countdown not configured in Gladys.
2022-02-03T07:36:35+0100 <warn> handleMqttMessage.js:96 () Zigbee2mqtt device RadiateurSalleaManger, feature boost_heating_countdown_time_set not configured in Gladys.
2022-02-03T07:36:35+0100 <error> index.js:20 (process.<anonymous>) uncaughtException catched: uncaughtException
2022-02-03T07:36:35+0100 <error> index.js:21 (process.<anonymous>) Error: Zigbee2mqqt don't handle value "LOCK" for feature "mode".
    at convertValue (/src/server/services/zigbee2mqtt/utils/convertValue.js:55:17)
    at /src/server/services/zigbee2mqtt/lib/handleMqttMessage.js:92:24
    at Array.forEach (<anonymous>)
    at Zigbee2mqttManager.handleMqttMessage (/src/server/services/zigbee2mqtt/lib/handleMqttMessage.js:86:41)
    at MqttClient.<anonymous> (/src/server/services/zigbee2mqtt/lib/connect.js:53:12)
    at MqttClient.emit (events.js:400:28)
    at MqttClient._handlePublish (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:410:12)
    at work (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/src/server/services/zigbee2mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/src/server/services/zigbee2mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/src/server/services/zigbee2mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (internal/streams/readable.js:731:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
2022-02-03T07:37:48+0100 <info> calendar.requests.js:52 () CalDAV : Found calendar [redacted]@gmail.com
2022-02-03T07:37:48+0100 <info> calendar.requests.js:52 () CalDAV : Found calendar [redacted]@gmail.com
2022-02-03T07:37:48+0100 <info> calendar.requests.js:52 () CalDAV : Found calendar Contacts
2022-02-03T07:37:48+0100 <info> calendar.requests.js:52 () CalDAV : Found calendar PERSO
2022-02-03T07:37:48+0100 <info> calendar.requests.js:52 () CalDAV : Found calendar Jours fériés en France
2022-02-03T07:37:48+0100 <info> calendar.syncUserCalendars.js:38 (CalDAVHandler.syncUserCalendars) CalDAV : Found 5 calendars.
2022-02-03T07:38:11+0100 <warn> connect.js:44 (MqttClient.<anonymous>) Disconnected from MQTT server
2022-02-03T07:38:16+0100 <info> connect.js:24 (MqttClient.<anonymous>) Connected to MQTT container mqtt://localhost:1884
2022-02-03T07:38:16+0100 <info> subscribe.js:12 (Zigbee2mqttManager.subscribe) Subscribing to MQTT topic zigbee2mqtt/#
2022-02-03T07:38:16+0100 <warn> handleMqttMessage.js:96 () Zigbee2mqtt device RadiateurChEnfants, feature boost_heating not configured in Gladys.
2022-02-03T07:38:16+0100 <warn> handleMqttMessage.js:96 () Zigbee2mqtt device RadiateurChEnfants, feature boost_heating_countdown not configured in Gladys.
2022-02-03T07:38:16+0100 <warn> handleMqttMessage.js:96 () Zigbee2mqtt device RadiateurChEnfants, feature boost_heating_countdown_time_set not configured in Gladys.
2022-02-03T07:38:16+0100 <error> index.js:20 (process.<anonymous>) uncaughtException catched: uncaughtException
2022-02-03T07:38:16+0100 <error> index.js:21 (process.<anonymous>) Error: Zigbee2mqqt don't handle value "LOCK" for feature "mode".
    at convertValue (/src/server/services/zigbee2mqtt/utils/convertValue.js:55:17)
    at /src/server/services/zigbee2mqtt/lib/handleMqttMessage.js:92:24
    at Array.forEach (<anonymous>)
    at Zigbee2mqttManager.handleMqttMessage (/src/server/services/zigbee2mqtt/lib/handleMqttMessage.js:86:41)
    at MqttClient.<anonymous> (/src/server/services/zigbee2mqtt/lib/connect.js:53:12)
    at MqttClient.emit (events.js:400:28)
    at MqttClient._handlePublish (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:410:12)
    at work (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:321:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
2022-02-03T07:40:16+0100 <warn> connect.js:44 (MqttClient.<anonymous>) Disconnected from MQTT server
2022-02-03T07:40:21+0100 <info> connect.js:24 (MqttClient.<anonymous>) Connected to MQTT container mqtt://localhost:1884
2022-02-03T07:40:21+0100 <info> subscribe.js:12 (Zigbee2mqttManager.subscribe) Subscribing to MQTT topic zigbee2mqtt/#

```

**Comment by LM1LC3N7** [comment]
Hello again,

I have another error of that type, using the last dev image:

```bash
2022-03-01T12:48:08+0100 <error> handleMqttMessage.js:97 () Failed to convert value for device RadiateurSalon: Error: Zigbee2mqqt don't handle value "LOCK" for feature "mode".
    at convertValue (/src/server/services/zigbee2mqtt/utils/convertValue.js:55:17)
    at /src/server/services/zigbee2mqtt/lib/handleMqttMessage.js:93:26
    at Array.forEach (<anonymous>)
    at Zigbee2mqttManager.handleMqttMessage (/src/server/services/zigbee2mqtt/lib/handleMqttMessage.js:86:41)
    at MqttClient.<anonymous> (/src/server/services/zigbee2mqtt/lib/connect.js:53:12)
    at MqttClient.emit (events.js:400:28)
    at MqttClient._handlePublish (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:410:12)
    at work (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/src/server/services/zigbee2mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/src/server/services/zigbee2mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/src/server/services/zigbee2mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (internal/streams/readable.js:731:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by Pierre-Gilles** [comment]
@LM1LC3N7 Maybe create a new issue ? this issue is closed so it won't be looked at :)

**Comment by LM1LC3N7** [comment]
https://github.com/GladysAssistant/Gladys/issues/1448

**Comment by Pierre-Gilles** [comment]
FYI, I merged the PR and the fix today, and just started a Docker build on gladysassistant/gladys:dev

https://github.com/GladysAssistant/Gladys/actions/runs/2078334755

I'm looking for testers before I deploy this to prod just to make sure the final version is fine :)
