### ISSUE TITLE
Test fails randomly on Gateway backups "cannot start a transaction within a transaction"

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1483]
```
  1) gateway
       gateway.backup
         should backup gladys:
     SequelizeDatabaseError: SQLITE_ERROR: cannot start a transaction within a transaction
      at Query.formatError (node_modules/sequelize/lib/dialects/sqlite/query.js:415:16)
      at Query._handleQueryResponse (node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
      at Statement.afterExecute (node_modules/sequelize/lib/dialects/sqlite/query.js:246:27)
```

**Comment by Pierre-Gilles** [comment]
See if this can help: https://github.com/mapbox/node-sqlite3/wiki/Control-Flow#databaseserializecallback
