### ISSUE TITLE
Error after playing sound

### ISSUE THREAD

**Issue by lTimeLordl** [GladysAssistant/Gladys#15]
I tested the alarm.js script and i have this error after playing : 

``` events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Player.EventEmitter.emit (events.js:74:15)
    at Player.next (/home/pi/gladys/node_modules/player/dist/player.js:242:14)
    at Decoder.<anonymous> (/home/pi/gladys/node_modules/player/dist/player.js:167:25)
    at Decoder.g (events.js:175:14)
    at Decoder.EventEmitter.emit (events.js:117:20)
    at finishMaybe (/home/pi/gladys/node_modules/player/node_modules/lame/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at afterWrite (/home/pi/gladys/node_modules/player/node_modules/lame/node_modules/readable-stream/lib/_stream_writable.js:291:5)
    at onwrite (/home/pi/gladys/node_modules/player/node_modules/lame/node_modules/readable-stream/lib/_stream_writable.js:281:7)
    at WritableState.onwrite (/home/pi/gladys/node_modules/player/node_modules/lame/node_modules/readable-stream/lib/_stream_writable.js:106:5)
    at afterTransform (/home/pi/gladys/node_modules/player/node_modules/lame/node_modules/readable-stream/lib/_stream_transform.js:104:5)
    at TransformState.afterTransform (/home/pi/gladys/node_modules/player/node_modules/lame/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at handleRead (/home/pi/gladys/node_modules/player/node_modules/lame/lib/decoder.js:142:14)
    at afterRead (/home/pi/gladys/node_modules/player/node_modules/lame/lib/decoder.js:121:7)
```

**Comment by Pierre-Gilles** [comment]
Thanks for the feedback, just fixed :)

Git pull to get the modification.

**Comment by lTimeLordl** [comment]
Thanks
