### ISSUE TITLE
Alexa integration: crash on handleAlexaMessage

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#1547]
```
2022-05-24T22:03:59+0200 <error> gateway.handleAlexaMessage.js:52 (Gateway.handleAlexaMessage) Error: WHERE parameter "name" has invalid "undefined" value
    at SQLiteQueryGenerator.whereItemQuery (/src/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1655:13)
    at /src/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1646:25
    at Array.forEach (<anonymous>)
    at SQLiteQueryGenerator.whereItemsQuery (/src/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1644:35)
    at SQLiteQueryGenerator.getWhereConditions (/src/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1987:19)
    at SQLiteQueryGenerator.selectQuery (/src/server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:932:28)
    at SQLiteQueryInterface.select (/src/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:396:59)
    at Function.findAll (/src/server/node_modules/sequelize/lib/model.js:1128:47)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Function.findOne (/src/server/node_modules/sequelize/lib/model.js:1222:12)
    at async Variable.setValue (/src/server/lib/variable/variable.setValue.js:15:20)
    at async Gateway.handleAlexaMessage (/src/server/lib/gateway/gateway.handleAlexaMessage.js:28:7)
```

**Comment by Pierre-Gilles** [comment]
Not linked to Gladys but a fork.
