### ISSUE TITLE
Scenarios, errors when execute a script alarm.js

### ISSUE THREAD

**Issue by lTimeLordl** [GladysAssistant/Gladys#16]
```
info: ScenarioService : launcher : alarmRing : 4
info: Launch action : ScriptService exec alarm.js
info: Playing : music/******.mp3
warn: In script error TypeError: undefined is not a function

/home/pi/gladys/api/services/ScriptService.js:95
                    if(err) return callback(err);
                                   ^
TypeError: undefined is not a function
    at /home/pi/gladys/api/services/ScriptService.js:95:21
    at Object.module.exports.sandbox (/home/pi/gladys/api/services/ScriptService.js:117:5)
    at Object.bound [as sandbox] (/home/pi/gladys/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /home/pi/gladys/api/services/ScriptService.js:94:19
    at /home/pi/gladys/api/services/ScriptService.js:72:4
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
```

**Comment by Pierre-Gilles** [comment]
That's an issues, a little line will fix that :)

I correct it right now. Thanks for the feedback !

**Comment by Pierre-Gilles** [comment]
Fixed :)

**Comment by lTimeLordl** [comment]
Thanks
