### ISSUE TITLE
Impossible d'accéder à l'interface

### ISSUE THREAD

**Issue by ghost** [GladysAssistant/Gladys#160]
Bonjour, 

J'ai l'erreur 502 depuis 1 heure après avoir fait un reboot pour Forecast. Voici mes logs
Est ce que tout est normal ?

```
[TAILING] Tailing last 10 lines for [gladys] process (change the value with --lines option)
/home/pi/.pm2/logs/gladys-out-0.log last 10 lines:
0|gladys   | Installing NPM dependencies for module forecast
0|gladys   | Gladys module forecast already cloned, skipping to install.
0|gladys   | Installing NPM dependencies for module forecast
0|gladys   | Dependencies installed for module forecast
0|gladys   | Module forecast installed with success. Need reboot.
0|gladys   | Dependencies installed for module forecast
0|gladys   | Module forecast installed with success. Need reboot.
0|gladys   | Gladys version : 3.1.11
0|gladys   | Gladys brain loaded with success !
0|gladys   | New version of Gladys available : 3.4.2

/home/pi/.pm2/logs/gladys-error-0.log last 10 lines:
0|gladys   | Error: Pool is closed.
0|gladys   |     at afterwards (/home/pi/gladys/node_modules/gladys/node_modules/sails-mysql/lib/connections/spawn.js:72:13)
0|gladys   |     at /home/pi/gladys/node_modules/gladys/node_modules/sails-mysql/lib/connections/spawn.js:40:7
0|gladys   |     at Handshake.onConnect (/home/pi/gladys/node_modules/gladys/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:54:9)
0|gladys   |     at Handshake.Sequence.end (/home/pi/gladys/node_modules/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
0|gladys   |     at /home/pi/gladys/node_modules/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:399:18
0|gladys   |     at Array.forEach (native)
0|gladys   |     at /home/pi/gladys/node_modules/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:398:13
0|gladys   |     at nextTickCallbackWith0Args (node.js:420:9)
0|gladys   |     at process._tickDomainCallback (node.js:390:13)

[STREAMING] Now streaming realtime logs for [gladys] process
```

**Comment by Pierre-Gilles** [comment]
`Error: Pool is closed.` indique que le pool MySQL est fermé, essaie de relancer Gladys, ou rebooter ton Raspberry Pi, ça devrait fixer l'issue.. je note le problème tout de même, ce n'est pas normal.
