### ISSUE TITLE
Multiple error with Gladys

### ISSUE THREAD

**Issue by Helo3615** [GladysAssistant/Gladys#171]
I just tried to do the update from 3.3.2 to the last one.

```
pi@gladys:~/gladys/node_modules/gladys $ sudo ./rpi-update.sh
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2][ERROR] Process gladys not found
^Cpi@gladys:~/gladys/node_modules/gladys $ chmod +x rpi-update.sh
pi@gladys:~/gladys/node_modules/gladys $ sudo ./rpi-update.sh
[PM2][ERROR] Process gladys not found
^Cpi@gladys:~/gladys/node_modules/gladys $ chmod +x rpi-update.sh
pi@gladys:~/gladys/node_modules/gladys $ ./rpi-update.sh
[PM2] Applying action stopProcessId on app [gladys](ids: 0)
[PM2] [gladys](0) ✓
npm ERR! Linux 4.4.13-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "gladys"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path /home/pi/gladys/node_modules/gladys/www/favicon.ico
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink

npm ERR! Error: EACCES: permission denied, unlink '/home/pi/gladys/node_modules/gladys/www/favicon.ico'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, unlink '/home/pi/gladys/node_modules/gladys/www/favicon.ico']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/home/pi/gladys/node_modules/gladys/www/favicon.ico' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES: permission denied, rmdir '/home/pi/gladys/node_modules/gladys/www/concat'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES: permission denied, rmdir '/home/pi/gladys/node_modules/gladys/www/concat']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/home/pi/gladys/node_modules/gladys/www/concat' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/gladys/npm-debug.log
cp: cannot create directory ‘/home/pi/gladys/node_modules/gladys/api/hooks’: No such file or directory
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/pi/gladys/node_modules/gladys/init.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
[PM2] Applying action restartProcessId on app [gladys](ids: 0)
[PM2] [gladys](0) ✓
[PM2] Process successfully started
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ gladys   │ 0  │ fork │ 1614 │ online │ 0       │ 0s     │ 99% │ 12.7 MB   │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
pi@gladys:~/gladys/node_modules/gladys $ sudo ./rpi-update.sh
sudo: ./rpi-update.sh: command not found
pi@gladys:~/gladys/node_modules/gladys $ ls
cache  node_modules  www
pi@gladys:~/gladys/node_modules/gladys $
```
And... rpi-update.sh just disapear

**Comment by Pierre-Gilles** [comment]
Sorry for the late reply... there was an error during your update and Gladys files were deleted during the update. 

You can reinstall Gladys without losing your data (it's inside the DB ;)) just by doing: 

```
$ cd /home/pi/gladys
$ sudo rm -rf node_modules
$ npm install gladys
$ cd node_modules/gladys
$ node init.js
$ grunt buildProd
$ pm2 start /home/pi/gladys/node_modules/gladys/app.js --name gladys
```
