### ISSUE TITLE
error on start run

### ISSUE THREAD

**Issue by kalsolio** [GladysAssistant/Gladys#193]
```
Unhandled rejection Error: Param not found
    at /data/wwwroot/gladys/api/core/param/param.getValue.js:16:36
    at tryCatcher (/data/wwwroot/gladys/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/data/wwwroot/gladys/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/data/wwwroot/gladys/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/data/wwwroot/gladys/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/data/wwwroot/gladys/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/data/wwwroot/gladys/node_modules/bluebird/js/release/promise.js:636:18)
    at /data/wwwroot/gladys/node_modules/bluebird/js/release/nodeback.js:42:21
    at /data/wwwroot/gladys/node_modules/sails-mysql/lib/connections/spawn.js:120:16
    at Object.poolfully [as releaseConnection] (/data/wwwroot/gladys/node_modules/sails-mysql/lib/connections/release.js:28:12)
    at Query._callback (/data/wwwroot/gladys/node_modules/sails-mysql/lib/connections/spawn.js:105:35)
    at Query.Sequence.end (/data/wwwroot/gladys/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/data/wwwroot/gladys/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/data/wwwroot/gladys/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/data/wwwroot/gladys/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/data/wwwroot/gladys/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/data/wwwroot/gladys/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/data/wwwroot/gladys/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)

```

**Comment by Pierre-Gilles** [comment]
You seems to have installed a gladys module without setting the asked variables ! Which modules have you installed ?

**Comment by Pierre-Gilles** [comment]
Is it resolved ? :) If yes, I'm closing this issue
