### ISSUE TITLE
Errors while starting on MACOSX

### ISSUE THREAD

**Issue by tuxx** [GladysAssistant/Gladys#195]
tuxxs-iMac:gladys tuxx$ sails lift

info: Starting app...

/Users/tuxx/gladys/config/update.js:15
    updateScript: process.env.UPDATE_SCRIPT_PATH || `${__dirname}/../rpi-updat
                                                    ^
`include-all` attempted to `require(/Users/tuxx/gladys/config/update.js)`, but an error occurred::
Details:SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/tuxx/gladys/node_modules/include-all/lib/help-include-all-sync.js:271:33
    at Array.forEach (native)
    at _recursivelyIncludeAll (/Users/tuxx/gladys/node_modules/include-all/lib/help-include-all-sync.js:174:11)
    at includeAll (/Users/tuxx/gladys/node_modules/include-all/lib/help-include-all-sync.js:292:5)
    at helpBuildDictionary (/Users/tuxx/gladys/node_modules/include-all/lib/help-build-dictionary.js:43:15)
    at Function.module.exports.aggregate (/Users/tuxx/gladys/node_modules/include-all/index.js:101:10)
    at Array.loadOtherConfigFiles [as 0] (/Users/tuxx/gladys/node_modules/sails/lib/hooks/moduleloader/index.js:247:22)
    at /Users/tuxx/gladys/node_modules/sails/node_modules/async/lib/async.js:591:38
    at _arrayEach (/Users/tuxx/gladys/node_modules/sails/node_modules/async/lib/async.js:85:13)
    at Object.async.auto (/Users/tuxx/gladys/node_modules/sails/node_modules/async/lib/async.js:552:9)
    at Hook.loadUserConfig (/Users/tuxx/gladys/node_modules/sails/lib/hooks/moduleloader/index.js:245:13)
    at Hook.wrapper [as loadUserConfig] (/Users/tuxx/gladys/node_modules/sails/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at Hook.loadModules (/Users/tuxx/gladys/node_modules/sails/lib/hooks/userconfig/index.js:41:27)
    at Hook.wrapper [as loadModules] (/Users/tuxx/gladys/node_modules/sails/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at Array.async.auto.modules [as 0] (/Users/tuxx/gladys/node_modules/sails/lib/hooks/index.js:79:27)
    at /Users/tuxx/gladys/node_modules/sails/node_modules/async/lib/async.js:591:38

**Comment by Pierre-Gilles** [comment]
Ta version de Node.js est trop ancienne ! Il faut Node.js au moins en version 4, je recommande la version 6 :)

**Comment by tuxx** [comment]
Thanks xD
