### ISSUE TITLE
Sonos Service is launching a Scan at Gladys startup

### ISSUE THREAD

**Issue by cicoub13** [GladysAssistant/Gladys#1968]
```
2023-12-07T16:27:45+0100 <error> index.js:15 (process.<anonymous>) unhandledRejection catched: Promise {
  <rejected> SonosDiscoveryError: No players found
      at EventEmitter.<anonymous> (/src/server/services/sonos/node_modules/@svrooij/sonos/lib/sonos-device-discovery.js:96:24)
      at Object.onceWrapper (node:events:631:28)
      at EventEmitter.emit (node:events:517:28)
      at Timeout.<anonymous> (/src/server/services/sonos/node_modules/@svrooij/sonos/lib/sonos-device-discovery.js:84:25)
      at listOnTimeout (node:internal/timers:569:17)
      at processTimers (node:internal/timers:512:7)
}
2023-12-07T16:27:45+0100 <error> index.js:16 (process.<anonymous>) SonosDiscoveryError: No players found
    at EventEmitter.<anonymous> (/src/server/services/sonos/node_modules/@svrooij/sonos/lib/sonos-device-discovery.js:96:24)
    at Object.onceWrapper (node:events:631:28)
    at EventEmitter.emit (node:events:517:28)
    at Timeout.<anonymous> (/src/server/services/sonos/node_modules/@svrooij/sonos/lib/sonos-device-discovery.js:84:25)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
```

**Comment by Pierre-Gilles** [comment]
@cicoub13 Yes this is wanted :)
