### ISSUE TITLE
Installation impossible sous Windows 8.1

### ISSUE THREAD

**Issue by hervehobbes** [GladysAssistant/Gladys#20]
Bonjour,

Je tente l'installation sous Windows 8.1 et j'ai plusieurs messages d'erreur :

Impossible de charger le fichier projet. Il existe un caractère non valide dans l'encodage donné. Ligne 47, position 50

Voir le log complet ci-dessous.

Une idée ?

Merci,
Hervé

``` javascript
λ npm install
npm WARN package.json crypto@0.0.3 crypto is also the name of a node core module.
-


> bcrypt@0.8.0 install F:\Gladys\node_modules\bcrypt
> node-gyp rebuild

|
F:\Gladys\node_modules\bcrypt {git}
{lamb} node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
F:\Gladys\node_modules\bcrypt\build\bcrypt_lib.vcxproj(47,50): error MSB4025: Impossible de charger le fichier projet. Il existe un caractère non valide dans l'encodage donné. Ligne 47, position 50.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Gladys\node_modules\bcrypt
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok



> speaker@0.2.5 install F:\Gladys\node_modules\speaker
> node-gyp rebuild


F:\Gladys\node_modules\speaker {git}
{lamb} node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
F:\Gladys\node_modules\speaker\build\deps\mpg123\output.vcxproj(42,50): error MSB4025: Impossible de charger le fichier projet. Il existe un caractère non valide dans l'encodage donné. Ligne 42, position 50.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Gladys\node_modules\speaker
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

> lame@1.1.2 install F:\Gladys\node_modules\lame
> node-gyp rebuild


F:\Gladys\node_modules\lame {git}
{lamb} node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Warning: Missing input files:
F:\Gladys\node_modules\lame\build\deps\mpg123\..\..\..\deps\mpg123\test_output.c
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
F:\Gladys\node_modules\lame\build\deps\lame\mp3lame.vcxproj(42,178): error MSB4025: Impossible de charger le fichier projet. Il existe un caractère non valide dans l'encodage donné. Ligne 42, position 178.
F:\Gladys\node_modules\lame\build\deps\mpg123\mpg123.vcxproj(42,50): error MSB4025: Impossible de charger le fichier projet. Il existe un caractère non valide dans l'encodage donné. Ligne 42, position 50.
F:\Gladys\node_modules\lame\build\deps\lame\lamevectorroutines.vcxproj(42,178): error MSB4025: Impossible de charger le fichier projet. Il existe un caractère non valide dans l'encodage donné. Ligne 42, position 178.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Gladys\node_modules\lame
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

> lame@1.2.2 install F:\Gladys\node_modules\player\node_modules\lame
> node-gyp rebuild


F:\Gladys\node_modules\player\node_modules\lame {git}
{lamb} node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Warning: Missing input files:
F:\Gladys\node_modules\player\node_modules\lame\build\deps\mpg123\..\..\..\deps\mpg123\test_output.c
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
F:\Gladys\node_modules\player\node_modules\lame\build\deps\lame\mp3lame.vcxproj(42,178): error MSB4025: Impossible de charger le fichier projet. Il existe un caractère non valide dans l'encodage donné. Ligne 42, position 178.
F:\Gladys\node_modules\player\node_modules\lame\build\deps\mpg123\mpg123.vcxproj(42,50): error MSB4025: Impossible de charger le fichier projet. Il existe un caractère non valide dans l'encodage donné. Ligne 42, position 50.
F:\Gladys\node_modules\player\node_modules\lame\build\deps\lame\lamevectorroutines.vcxproj(42,178): error MSB4025: Impossible de charger le fichier projet. Il existe un caractère non valide dans l'encodage donné. Ligne 42, position 178.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Gladys\node_modules\player\node_modules\lame
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Gladys\npm-debug.log

F:\Gladys
λ

```

**Comment by Pierre-Gilles** [comment]
C'est un problème de compilation de modules, certaines modules node.js sont écris en C++ et compilé sur la machine où le module est installé.
- Avez-vous bien un compilateur c++ sur votre machine ? ( Visual Studio comme indiqué dans les dépendances de Gladys ? )

Sinon regardez de ce côté là : https://github.com/node-inspector/v8-profiler/issues/47#issuecomment-68006525

Installer les modules avec l'option `npm install --msvs_version=2013` pourrait régler le problème, dites moi !

**Comment by hervehobbes** [comment]
Bonjour,

J'ai Visual Studio Community 2013 installé.

**Comment by hervehobbes** [comment]
Sur une autre machine, elle aussi sous Windows 8.1, je suis allé plus loin, j'ai pu terminé l'installation en réinstallant une version plus récente de Node.js mais maintenant j'ai l'erreur suivante:

``` javascript
λ node app.js
info: User hook policies loaded from C:\gladys\api\hooks\example/policies.
info: User hook config loaded from C:\gladys\api\hooks\example/config.
C:\gladys\node_modules\bindings\bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 ÔåÆ C:\gladys\node_modules\player\node_modules\lame\build\bindings.node
 ÔåÆ C:\gladys\node_modules\player\node_modules\lame\build\Debug\bindings.node
 ÔåÆ C:\gladys\node_modules\player\node_modules\lame\build\Release\bindings.node
 ÔåÆ C:\gladys\node_modules\player\node_modules\lame\out\Debug\bindings.node
 ÔåÆ C:\gladys\node_modules\player\node_modules\lame\Debug\bindings.node
 ÔåÆ C:\gladys\node_modules\player\node_modules\lame\out\Release\bindings.node
 ÔåÆ C:\gladys\node_modules\player\node_modules\lame\Release\bindings.node
 ÔåÆ C:\gladys\node_modules\player\node_modules\lame\build\default\bindings.node
 ÔåÆ C:\gladys\node_modules\player\node_modules\lame\compiled\0.12.4\win32\x64\bindings.node
    at bindings (C:\gladys\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (C:\gladys\node_modules\player\node_modules\lame\lib\bindings.js:1:99)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\gladys\node_modules\player\node_modules\lame\lib\decoder.js:7:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\gladys\node_modules\player\node_modules\lame\index.js:6:19)
```

**Comment by Pierre-Gilles** [comment]
Justement il faut installer Gladys en node 0.10.xx car le module player, et lame supporte mal node 0.12 !

**Comment by hervehobbes** [comment]
Ok, je ferais des test plus tard 

Encore merci.

**Comment by VonOx** [comment]
Pour node en 0.10 ==> http://nodejs.org/dist/v0.10.38/

PS: J'ai réussi une installation fonctionnelle sur un Win 8.1 et VS 2013 Pro
