### ISSUE TITLE
Unable to integrate Tuya

### ISSUE THREAD

**Issue by Schokolade-spec** [GladysAssistant/Gladys#2093]
**Describe the bug**
When I scan Tuya devices on Gladys Assistant it doesn't show anything even though everything is configured.

**To Reproduce**

1. Go to 'Integrations' and 'Tuya'.
2. Click on 'Découverte Tuya' and 'Scanner'.

**Logs**
2024-06-02T20:10:09+0200 <error> tuya.discoverDevices.js:38 (TuyaHandler.discoverDevices) Unable to load Tuya devices TypeError: Cannot destructure property 'list' of 'result' as it is undefined.
    at TuyaHandler.loadDevices (/src/server/services/tuya/lib/tuya.loadDevices.js:25:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TuyaHandler.discoverDevices (/src/server/services/tuya/lib/tuya.discoverDevices.js:35:15)
    at discover (/src/server/services/tuya/api/tuya.controller.js:10:21)

**Your Gladys installation (please complete the following information):**
- Raspberry Pi 4

**Comment by Pierre-Gilles** [comment]
Thanks for your message!
What kind of Tuya devices are you using?
Would you mind sharing your Tuya credentials in private message so i can reproduce?

Thanks a lot 🙏

**Comment by Schokolade-spec** [comment]
Solved, the Raspberry Pi didn't seems to be connected to Internet.
