### ISSUE TITLE
Installation impossible sur Raspberry Pi

### ISSUE THREAD

**Issue by hervehobbes** [GladysAssistant/Gladys#21]
Bonjour,

J'ai aussi des problèmes d'installation sur un Raspberry Pi.
Ma raspbian est en version "Jessie"
Voilà le log complet :

``` javascript
> bcrypt@0.8.0 install /home/pi/Gladys/node_modules/bcrypt
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.18.11+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/Gladys/node_modules/bcrypt
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian


> sails@0.11.0 preinstall /home/pi/Gladys/node_modules/sails
> node ./lib/preinstall_npmcheck.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! bcrypt@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.0 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.18.11+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Gladys
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
/
> speaker@0.2.5 install /home/pi/Gladys/node_modules/speaker
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.18.11+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/Gladys/node_modules/speaker
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

/
> serialport@1.7.4 install /home/pi/Gladys/node_modules/serialport
> node-pre-gyp install --fallback-to-build

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

-
> lame@1.2.2 install /home/pi/Gladys/node_modules/player/node_modules/lame
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.18.11+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/Gladys/node_modules/player/node_modules/lame
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Gladys/npm-debug.log
npm ERR! not ok code 0
root@raspberrypi1:/home/pi/Gladys#

```

**Comment by Pierre-Gilles** [comment]
Comment avez vous installé Node.js ? Le code d'erreur spécifie qu'il y a un problème avec node.js ( This failure might be due to the use of legacy binary "node" )

**Comment by hervehobbes** [comment]
Comme ceci :
apt-get install node

**Comment by Pierre-Gilles** [comment]
Ah je vois ! Préférez plutôt le script d'installation pour Raspberry Pi de Gladys : https://github.com/GladysProject/Gladys/blob/master/rpi-install.sh 

Pour installer node.js sur un Raspberry Pi il est recommandé d'utiliser le packet précompilé pour processeur ARM ( http://node-arm.herokuapp.com/ ), plutôt que de passer par apt-get. 

```
wget http://node-arm.herokuapp.com/node_0.10.36_armhf.deb
sudo dpkg -i node_0.10.36_armhf.deb
```

**Comment by hervehobbes** [comment]
Ok, ça marche.
Il m'a fallu installer Sails dans le répertoire de Gladys pour que cela marche.
Par contre une fois connecté au site, je n'ai aucune feuille de style et images...

Merci en tout cas.

**Comment by Pierre-Gilles** [comment]
Vous devez avoir une erreur grunt dans votre console, si les styles ne sont pas présents c'est que grunt n'a pas pu copier les fichiers statique dans le dossier ".tmp", c'est souvent un problème de droit

**Comment by hervehobbes** [comment]
Bonsoir,

Effectivement, il y avait quelques messages dans la console, j'ai du installer, en local, grunt-contrib-coffee, less, uglify et changer les droits sur le répertoire .tmp

Merci pour l'aide !

**Comment by Pierre-Gilles** [comment]
Ces modules sont dans le package.json et s'installent tout seul "en théorie" lors du npm install, après desfois tout ne s'installe pas correctement. 

Content que ça fonctionne au final !

**Comment by hervehobbes** [comment]
Merci pour toute l'aide apportée !
