### ISSUE TITLE
Erreur démarrage serveur après installation module

### ISSUE THREAD

**Issue by f3dora19** [GladysAssistant/Gladys#219]
Bonjour,

J'ai cette erreur lorsque je redémarre le serveur après avoir installé un module depuis Gladys :
```javascript
module.js:341
    throw err;
    ^

Error: Cannot find module '@google/maps'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Luc\Documents\2 - Perso\Gladys\api\hooks\google-direction\lib\init.js:1:82)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.module.exports (C:\Users\Luc\Documents\2 - Perso\Gladys\api\hooks\google-direction\index.js:3:16)
    at wrapper (C:\Users\Luc\Documents\2 - Perso\Gladys\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at prepareHook (C:\Users\Luc\Documents\2 - Perso\Gladys\node_modules\sails\lib\app\private\loadHooks.js:45:17)
    at C:\Users\Luc\Documents\2 - Perso\Gladys\node_modules\sails\lib\app\private\loadHooks.js:149:13
    at C:\Users\Luc\Documents\2 - Perso\Gladys\node_modules\sails\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (C:\Users\Luc\Documents\2 - Perso\Gladys\node_modules\sails\node_modules\async\lib\async.js:233:13)
    at Object.async.forEach.async.each (C:\Users\Luc\Documents\2 - Perso\Gladys\node_modules\sails\node_modules\async\lib\async.js:209:22)
    at async.series.prepare (C:\Users\Luc\Documents\2 - Perso\Gladys\node_modules\sails\lib\app\private\loadHooks.js:148:17)
    at C:\Users\Luc\Documents\2 - Perso\Gladys\node_modules\sails\node_modules\async\lib\async.js:713:13
    at iterate (C:\Users\Luc\Documents\2 - Perso\Gladys\node_modules\sails\node_modules\async\lib\async.js:262:13)
    at C:\Users\Luc\Documents\2 - Perso\Gladys\node_modules\sails\node_modules\async\lib\async.js:274:29
```

J'ai réussi à résoudre le problème en installant le module demandé à la main et une fois le serveur éteint avec la commande suivante : 
```javascript
npm install @google/maps
```

Il semblerai que les dépendances ne s'installent pas correctement malgré le message :
```javascript
info: Dependencies installed for module google-direction
info: Module google-direction installed with success. Need reboot.
```

Pour info, j'ai eu le même souci avec le module MQTT.

**Comment by Pierre-Gilles** [comment]
Tu es sous Windows visiblement, les modules compilées ont en effet parfois des problèmes d'installation sous Windows.. 

Pourtant le module est bien dans les dépendances ( cf  => https://github.com/GladysProject/gladys-google-direction/blob/master/package.json#L8 ) et devrait être installé lors de son installation

Je garde le problème dans un coin de ma tête, si jamais tu as plus d'infos sur le problème n'hésite pas à revenir vers moi ici :) Je ne pourrais pas reproduire le bug je n'ai pas de PC windows :/
