### ISSUE TITLE
Can't run gladys

### ISSUE THREAD

**Issue by kalon33** [GladysAssistant/Gladys#231]
Starting Gladys (after setting it up using instructions from [here](https://developer.gladysproject.com/fr/documentation/install-gladys), I got this error:

```
node init.js && grunt buildProd
error: A hook (`orm`) failed to load!
Error (E_UNKNOWN) :: Encountered an unexpected error
: ER_GET_ERRNO: Got error 28 from storage engine
    at Query.Sequence._packetToError (/root/gladys/node_modules/sails-m
sql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/root/gladys/node_modules/sails-mysql/node_mo
ules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/root/gladys/node_modules/sails-mysql/nod
_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/root/gladys/node_modules/sails-mysql/node_modules
mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/root/gladys/node_modules/sails-mysql/node_modul
s/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/gladys/node_modules/sails-mysql/node_m
dules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
    --------------------
    at Protocol._enqueue (/root/gladys/node_modules/sails-mysql/node_mo
ules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (/root/gladys/node_modules/sails-mysql/node
modules/mysql/lib/Connection.js:201:25)
    at __DESCRIBE__ (/root/gladys/node_modules/sails-mysql/lib/adapter.
s:139:20)
    at afterwards (/root/gladys/node_modules/sails-mysql/lib/connection
/spawn.js:84:5)
    at /root/gladys/node_modules/sails-mysql/lib/connections/spawn.js:4
:7
    at Handshake.onConnect [as _callback] (/root/gladys/node_modules/sa
ls-mysql/node_modules/mysql/lib/Pool.js:59:7)
    at Handshake.Sequence.end (/root/gladys/node_modules/sails-mysql/no
e_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.Sequence.OkPacket (/root/gladys/node_modules/sails-mys
l/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/root/gladys/node_modules/sails-mysql/nod
_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/root/gladys/node_modules/sails-mysql/node_modules
mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/root/gladys/node_modules/sails-mysql/node_modul
s/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/gladys/node_modules/sails-mysql/node_m
dules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)

Details:  Error: ER_GET_ERRNO: Got error 28 from storage engine
```

I checked mysql user and password and they are ok. What's the problem? I edited connections.js to add my credentials.

**Comment by kalon33** [comment]
I have the same error setting environment variables.

**Comment by kalon33** [comment]
Was due to insufficient space on my root partition, sorry. Closing.
