### ISSUE TITLE
Probleme d'instalation

### ISSUE THREAD

**Issue by ghost** [GladysAssistant/Gladys#270]
Bonjour,
J'ai un probleme lors de l'instalation de gladys, j'ai suivie ce tuto : 
https://community.gladysproject.com/t/tutoriel-installation-gladys-from-scratch-sur-raspbian-lite/1811
et au moment crucial de faire `node init.js` il me dit qu'il faut mettre son mdp mysql mais ou le met on ?

l'erreur (regarder juste les 2 derniere ligne): 

error: A hook (`orm`) failed to load!
Error (E_UNKNOWN) :: Encountered an unexpected error
: Could not connect to MySQL:
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at afterwards (/gladys/node_modules/sails-mysql/lib/connections/spawn.js:72:13)
    at /gladys/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at Handshake.onConnect (/gladys/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:54:9)
    at Handshake.Sequence.end (/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.ErrorPacket (/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:8)
    at Protocol._parsePacket (/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/gladys/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

Details:  Error: Could not connect to MySQL:
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)

ps: j'ai essayer avec 'sudo node init.js' mais sa ne change rien

**Comment by ghost** [comment]
c'est bon probleme resole, il faut changer le mdp de mysql en "root"

**Comment by mixman68** [comment]
Le problème de ce script est qu'il tente tout le temps de se lancer sur 'linstance locale, j'ai du faire ça puis dump la base et la restaurer sur le vrai serveur mysql

**Comment by dikkedimi** [comment]
Using french is really _impractical_ for other people that have learned actual world languages. Please use English as it helps others find solutions easier.

Anyway, I have the same issue.
- I changed the password of my 'root' account on my database server and created a 'gladys' user
with all privileges on the gladys database
- I have configured gladys's own user in the .env file
Why does it try to connect on root? I have granted all privileges to the user gladys AND configured my .env variables.

It should not be necessary to use the root account.

**Comment by Boimb** [comment]
Hi @dikkedimi ,
Never managed to get that .env working, but i'm fine with env vars : 

```
export MYSQL_USER=db_username
export MYSQL_PASSWORD=db_pass
```

Or insert that into a script that runs at startup to keep settings after reboot : 

`sudo nano /etc/profile.d/gladys.sh
`

> 
> #!/bin/bash
> 
> MYSQL_USER=db_username
> MYSQL_PASSWORD=db_pass
> 
> export MYSQL_USER
> export MYSQL_PASSWORD

Hope this help.
Cheers

**Comment by dikkedimi** [comment]
I will give it a try tonight :) Thanks for the reference and reply!

**Comment by Pierre-Gilles** [comment]
Thanks for your answer @Boimb ! 

Is the issue solved ? Can I close it ?
