### ISSUE TITLE
can't execute the init file

### ISSUE THREAD

**Issue by dikkedimi** [GladysAssistant/Gladys#277]
When running node init.js the following result is yielded:

```
$ node init.js
error: A hook (`orm`) failed to load!
Error (E_UNKNOWN) :: Encountered an unexpected error
: Could not connect to MySQL:
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at afterwards (/home/pi/gladys/node_modules/sails-mysql/lib/connections/spawn.js:72:13)
    at /home/pi/gladys/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at Handshake.onConnect (/home/pi/gladys/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:54:9)
    at Handshake.Sequence.end (/home/pi/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.ErrorPacket (/home/pi/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:8)
    at Protocol._parsePacket (/home/pi/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/pi/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/home/pi/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/pi/gladys/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

Details:  Error: Could not connect to MySQL:
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
```

- I have set my environment variables in .env
- I have created database gladys with user gladys with all privileges. As configured in .env
- it still tries to connect using root, and says it fails. Yet logging in via command line works fine;
```
$ mysql -p -u root
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 25
Server version: 10.1.23-MariaDB-9+deb9u1 Raspbian 9.0

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> 

```
- where is hook orm?

**Comment by Boimb** [comment]
Related to #270

**Comment by Pierre-Gilles** [comment]
Node init.js is not supposed to use the .env file ! 

.env file is only here for the development process of Gladys itself !

So it's normal if the .env file is not loaded :)
