### ISSUE TITLE
Can't access module settings after install

### ISSUE THREAD

**Issue by fabfo** [GladysAssistant/Gladys#279]
Hello, 
I can't access any module settings after installation. I need to restart gladys.
If not I get the following error :

> Server Error:
TypeError: Cannot read property 'setup' of undefined
    at Object.module.exports [as config] (/root/gladys/api/core/module/module.config.js:5:43)
    at Object.config (/root/gladys/api/controllers/ModuleController.js:35:23)
    at wrapper (/root/gladys/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at routeTargetFnWrapper (/root/gladys/node_modules/sails/lib/router/bind.js:181:5)
    at callbacks (/root/gladys/node_modules/@sailshq/express/lib/router/index.js:164:37)
    at param (/root/gladys/node_modules/@sailshq/express/lib/router/index.js:138:11)
 ...

Is it normal ?

**Comment by Pierre-Gilles** [comment]
This is an issue with the module itself, not with Gladys! 
We need to know: Which module were you installing ? How have you installed it ? (manually or automatically). 

As GitHub is not the easiest way to debug, please post on Gladys forum here => http://community.gladysproject.com/ 

Thanks! :)
