### ISSUE TITLE
Erreur lors de l'exécution de l'application (/node_modules/bcrypt/node_modules/bindings/bindings.js:87)

### ISSUE THREAD

**Issue by PifyZ** [GladysAssistant/Gladys#4]
Bonjour,

lorsque j'essaye d'exécuter l'application après suivi la procédure d'installation, j'ai l'erreur suivante :

```
info: User hook policies loaded from /home/Pi/Programmation/Javascript/gladys/api/hooks/example/policies.
info: User hook config loaded from /home/Pi/Programmation/Javascript/gladys/api/hooks/example/config.

/home/Pi/Programmation/Javascript/gladys/node_modules/bcrypt/node_modules/bindings/bindings.js:87
  throw err
        ^
Error: Could not load the bindings file. Tried:
 → /home/Pi/Programmation/Javascript/gladys/node_modules/bcrypt/build/bcrypt_lib.node
 → /home/Pi/Programmation/Javascript/gladys/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /home/Pi/Programmation/Javascript/gladys/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /home/Pi/Programmation/Javascript/gladys/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /home/Pi/Programmation/Javascript/gladys/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /home/Pi/Programmation/Javascript/gladys/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /home/Pi/Programmation/Javascript/gladys/node_modules/bcrypt/Release/bcrypt_lib.node
 → /home/Pi/Programmation/Javascript/gladys/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /home/Pi/Programmation/Javascript/gladys/node_modules/bcrypt/compiled/0.10.25/linux/x64/bcrypt_lib.node
    at bindings (/home/Pi/Programmation/Javascript/gladys/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/home/Pi/Programmation/Javascript/gladys/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/Pi/Programmation/Javascript/gladys/api/controllers/SessionController.js:18:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/Pi/Programmation/Javascript/gladys/node_modules/include-all/index.js:129:29
```

Que dois-je faire ? L'erreur semble venir d'un module.

**Comment by Pierre-Gilles** [comment]
The issues is known :) We are talking about that [here](http://gladysproject.com/forum/viewtopic.php?f=23&t=5937) ! A correction is coming.

**Comment by Pierre-Gilles** [comment]
The corrections are pushed ! Git pull the change to avoid this bug.
