### ISSUE TITLE
Failed to lift app: v 3.10.3

### ISSUE THREAD

**Issue by varunsikka** [GladysAssistant/Gladys#436]
First, are you sure that you found a Gladys bug?

If you are not sure, you can come discuss with us on [Gladys Community Forum](http://community.gladysproject.com/) 🙂

**Describe the bug**
Getting error while running `node init.js`
```
error: Bootstrap encountered an error: (see below)
error: Failed to lift app: ReferenceError: User is not defined
    at Object.<anonymous> (/Users/varunsikka/workspace/smart-home/Gladys/api/core/utils/utils.sql.js:2:29)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/varunsikka/workspace/smart-home/Gladys/api/core/utils/index.js:2:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at EventEmitter.load (/Users/varunsikka/workspace/smart-home/Gladys/api/core/index.js:61:18)
    at Object.module.exports.bootstrap (/Users/varunsikka/workspace/smart-home/Gladys/config/bootstrap.js:15:10)
    at /Users/varunsikka/workspace/smart-home/Gladys/node_modules/sails/lib/app/private/bootstrap.js:68:22
    at Sails.runBootstrap (/Users/varunsikka/workspace/smart-home/Gladys/node_modules/sails/lib/app/private/bootstrap.js:71:5)
    at Sails.wrapper [as runBootstrap] (/Users/varunsikka/workspace/smart-home/Gladys/node_modules/@sailshq/lodash/lib/index.js:3275:19)
    at Sails.initialize (/Users/varunsikka/workspace/smart-home/Gladys/node_modules/sails/lib/app/private/initialize.js:67:9)
```

**To Reproduce**

**Expected behavior**
Running node init.js should install the database tables.

**Screenshots**
<img width="859" alt="screen shot 2018-10-29 at 9 35 05 pm" src="https://user-images.githubusercontent.com/6691401/47689980-9da86f80-dbc2-11e8-9278-7d9901b18377.png">

**Your Gladys installation (please complete the following information):**
 - Raspberry Pi installation (if yes, which Raspberry Pi ?)
 - Manual installation: [MacOS/Windows/Linux?] MacOS

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22] npm v6.4.1, node 8.5.0

**Additional context**

**Comment by varunsikka** [comment]
Removed and reinstalled, works fine.

**Comment by Pierre-Gilles** [comment]
Sorry for not responding fast enough, if you want support from the community, best is to ask on our online community :) GitHub is more for bug tracking/feature request

https://community.gladysproject.com/
