### ISSUE TITLE
Impossible to add a Telegram API key if you added a wrong one previously

### ISSUE THREAD

**Issue by thib-rdr** [GladysAssistant/Gladys#510]
**Describe the bug**
After adding a wrong API key in the telegram bot configuration, the UI is blocked and I am never able to add the right one.

**To Reproduce**

1. Go to "Integrations"
2. Choose the "Communication" category
3. Choose "Telegram"
4. Deliberately enter a wrong api key
5. The UI is then blocked
Here is the errors from the logs : 

```
(node:66) UnhandledPromiseRejectionWarning: Error: ETELEGRAM: 404 Not Found
    at request.then.resp (/src/server/services/telegram/node_modules/node-telegram-bot-api/src/telegram.js:280:15)
    at tryCatcher (/src/server/services/telegram/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/src/server/services/telegram/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/src/server/services/telegram/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/src/server/services/telegram/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/src/server/services/telegram/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/src/server/services/telegram/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/src/server/services/telegram/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/src/server/services/telegram/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/src/server/services/telegram/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:66) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
error: [polling_error] {"code":"ETELEGRAM","message":"ETELEGRAM: 404 Not Found"}
```

**Configuration**
- Raspberry PI 4/Raspbian buster
- Docker image

**Comment by Pierre-Gilles** [comment]
Nice catch!
