### ISSUE TITLE
Battle test device state creation

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#566]
SequelizeTimeoutError: SQLITE_BUSY: database is locked
at Query.formatError (/src/server/node_modules/sequelize/lib/dialects/sqlite/query.js:420:16)
at afterExecute (/src/server/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
at Statement.errBack (/src/server/node_modules/sqlite3/lib/sqlite3.js:16:21)
name: ‘SequelizeTimeoutError’,
parent:
{ Error: SQLITE_BUSY: database is locked
errno: 5,
code: ‘SQLITE_BUSY’,
sql:
‘INSERT INTO t_device_feature_state (id,device_feature_id,value,created_at,updated_at) VALUES (‘4bda35aa-b103-4463-b4e3-48db162f9780’,‘215500a7-ecef-40e0-b095-082c0a1f1ead’,21.5,‘2019-10-21 14:41:52.535 +00:00’,‘2019-10-21 14:41:52.535 +00:00’);’ },
original:
{ Error: SQLITE_BUSY: database is locked
errno: 5,
code: ‘SQLITE_BUSY’,
sql:
‘INSERT INTO t_device_feature_state (id,device_feature_id,value,created_at,updated_at) VALUES (‘4bda35aa-b103-4463-b4e3-48db162f9780’,‘215500a7-ecef-40e0-b095-082c0a1f1ead’,21.5,‘2019-10-21 14:41:52.535 +00:00’,‘2019-10-21 14:41:52.535 +00:00’);’ },
sql:
‘INSERT INTO t_device_feature_state (id,device_feature_id,value,created_at,updated_at) VALUES (‘4bda35aa-b103-4463-b4e3-48db162f9780’,‘215500a7-ecef-40e0-b095-082c0a1f1ead’,21.5,‘2019-10-21 14:41:52.535 +00:00’,‘2019-10-21 14:41:52.535 +00:00’);’ }

**Comment by Pierre-Gilles** [comment]
Fixed
