### ISSUE TITLE
Remove useless error log when deviceFeature does not exist yet in Gladys

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#612]
```
2019-11-19T10:15:48+0100 <error> device.newStateEvent.js:20 (DeviceManager.newStateEvent) Unable to save new state of deviceFeature zwave:node_id:10:comclass:113:index:2:instance:1, state = 0
2019-11-19T10:15:48+0100 <error> device.newStateEvent.js:23 (DeviceManager.newStateEvent) NotFoundError: DeviceFeature not found
    at DeviceManager.newStateEvent (/src/server/lib/device/device.newStateEvent.js:16:13)
    at EventEmitter.emit (events.js:210:5)
    at Event.emit (/src/server/lib/event/index.js:8:16)
    at ZwaveManager.valueChanged (/src/server/services/zwave/lib/events/zwave.valueChanged.js:25:23)
    at OZW.emit (events.js:210:5) {
  message: 'DeviceFeature not found'
}
```

**Comment by atrovato** [comment]
I saw logs changed to debug level, is this issues closed?

**Comment by Pierre-Gilles** [comment]
Yep, it is!
