### ISSUE TITLE
Problème d'installation :fichier lib/decoder

### ISSUE THREAD

**Issue by jeammimi** [GladysAssistant/Gladys#8]
Bonjour, 
après avoir lancer la commande npm install,
quand je lance node app.js j' ai l'erreur suivante:

Error: Cannot find module './lib/decoder'
une idée pour régler ce problème?

Merci
Ps: voila l'erreur complète:

[jm@bichito gladys]$ node app.js --help
info: User hook policies loaded from /home/jm/gladys/api/hooks/example/policies.
info: User hook config loaded from /home/jm/gladys/api/hooks/example/config.
module.js:338
    throw err;
    ^
Error: Cannot find module './lib/decoder'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/jm/gladys/node_modules/player/node_modules/lame/index.js:6:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/jm/gladys/node_modules/player/dist/player.js:51:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by Pierre-Gilles** [comment]
Un problème d'installation du module 'player' ! Essaie de réinstaller le module manuellement `npm install player` ;)

**Comment by jeammimi** [comment]
Je n'ai pas réussi a le réinstaller, mais une grande partie de mes problèmes
venaient du fait que j'avais python 3 par défaut.
En mettant python 2 par défault, j'ai réussi a installer gladys mais en désactivant le son car
je n'arrivais pas a installer lame.

**Comment by Pierre-Gilles** [comment]
L'installation de lame n'hésite pas à aller voir le github du module ( https://github.com/TooTallNate/node-lame ), ton problème n'est pas un cas isolé beaucoup de gens ont des problèmes avec ce module, et souvent on trouve des solutions pour sa machine dans les issues :) 

Tu as installé libasound2-dev comme indiqué dans la FAQ ?
