### ISSUE TITLE
[bluetooth] Service crash container at startup

### ISSUE THREAD

**Issue by VonOx** [GladysAssistant/Gladys#898]
I'm running amd64 container. ( no bluetooth on host )
```
> gladys-server@ start:prod /src/server
> cross-env NODE_ENV=production node index.js

Initialising OpenZWave 1.6.1051 binary addon for Node.JS.
        OpenZWave Security API is ENABLED
        ZWave device db    : /usr/local/etc/openzwave
        User settings path : /src/server/services/zwave/node_modules/openzwave-shared/build/Release/../../
        Option Overrides : --Logging false --ConsoleOutput false --SaveConfiguration true
2020-10-16T22:22:24+0200 <info> index.js:13 (Object.start) Starting usb service
2020-10-16T22:22:24+0200 <info> index.js:16 (Object.start) Starting zwave service
2020-10-16T22:22:24+0200 <info> index.js:15 (Object.start) Starting Bluetooth service
2020-10-16T22:22:24+0200 <info> index.js:19 (Object.start) Starting telegram service
2020-10-16T22:22:24+0200 <info> index.js:20 (Object.start) Starting Open Weather service

/src/server/services/bluetooth/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100
    this._deviceId = this._socket.bindRaw(deviceId);
                                  ^

Error: ENODEV, No such device
    at Hci.init (/src/server/services/bluetooth/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100:35)
    at NobleBindings.init (/src/server/services/bluetooth/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:78:13)
    at /src/server/services/bluetooth/node_modules/@abandonware/noble/lib/noble.js:60:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: 19,
  code: 'ENODEV',
  syscall: 'bind'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gladys-server@ start:prod: `cross-env NODE_ENV=production node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gladys-server@ start:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-16T20_07_23_616Z-debug.log

```

**Comment by atrovato** [comment]
Wow, nice approach, no Bluetooth on host !
I tought this would not crash Gladys...

**Comment by atrovato** [comment]
Issue create in Noble repo
https://github.com/abandonware/noble/issues/132

**Comment by atrovato** [comment]
@Pierre-Gilles I found something global to handle errors:

```
process.on('uncaughtException', (error, promise) => {
  logger.error('uncaughtException catched:', promise);
  logger.error(error);
});
```

I create a PR (and rollback the workaround to avoid service start on startup).

**Comment by Pierre-Gilles** [comment]
> I create a PR (and rollback the workaround to avoid service start on startup).

This workaround was great, no? Why shouldn't we keep it?

**Comment by atrovato** [comment]
With `process.on('uncaughtException'`, Gladys doesn't restart anymore, So we are not looping on service startup.
So I think this is not useful anymore, it going to be "dead code".

**Comment by Pierre-Gilles** [comment]
Are you sure it catches 100% of errors ? I'm really not sure.

C++ errors in native modules which makes the C++ crash make Node.js crash if I'm not mistaken. It happened to me with the Z-Wave integration for example..
