### ISSUE TITLE
Crash: Error: WebSocket is not open: readyState 3 (CLOSED)

### ISSUE THREAD

**Issue by Pierre-Gilles** [GladysAssistant/Gladys#931]
"Bonjour tout le monde !
Il vient de m’arriver un petit problème avec mon instance Gladys, j’ai consulté les logs de mon container :
Et voilà ce que j’obtiens (je précise que mon docker ps me montre que mon container est up mais quand je veux faire un exec dessus il me dit qu’il est stoppé :confused: )"

```
2020-11-09T02:46:54+0100 <warn> connect.js:60 (MqttClient.<anonymous>) Disconnected from MQTT server
/src/server/node_modules/ws/lib/websocket.js:335
      throw err;
      ^
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/src/server/node_modules/ws/lib/websocket.js:329:19)
    at /src/server/api/websockets/index.js:38:29
    at Array.forEach (<anonymous>)
    at /src/server/api/websockets/index.js:37:30
    at Array.forEach (<anonymous>)
    at WebsocketManager.sendMessageAllUsers (/src/server/api/websockets/index.js:36:12)
    at EventEmitter.<anonymous> (/src/server/api/websockets/index.js:10:67)
    at EventEmitter.emit (events.js:327:22)
    at Event.emit (/src/server/lib/event/index.js:8:16)
    at MqttClient.<anonymous> (/src/server/services/mqtt/lib/connect.js:61:23)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._setupReconnect (/src/server/services/mqtt/node_modules/mqtt/lib/client.js:933:12)
    at MqttClient.<anonymous> (/src/server/services/mqtt/node_modules/mqtt/lib/client.js:263:10)
    at MqttClient.emit (events.js:315:20)
    at Socket.<anonymous> (/src/server/services/mqtt/node_modules/mqtt/lib/client.js:350:10)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gladys-server@ start:prod: `cross-env NODE_ENV=production node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gladys-server@ start:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-09T01_47_47_980Z-debug.log
```

**Comment by Pierre-Gilles** [comment]
https://github.com/websockets/ws/issues/1724

We need to add: 

```
if (ws.readyState === WebSocket.OPEN) {
  ws.send(data);
}
```
